/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefoundRouteImport } from './routes/refound'
import { Route as Up1RouteImport } from './routes/up1'
import { Route as Up2RouteImport } from './routes/up2'
import { Route as WRouteImport } from './routes/w'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefoundRoute = RefoundRouteImport.update({
  id: '/refound',
  path: '/refound',
  getParentRoute: () => rootRouteImport,
} as any)
const Up1Route = Up1RouteImport.update({
  id: '/up1',
  path: '/up1',
  getParentRoute: () => rootRouteImport,
} as any)
const Up2Route = Up2RouteImport.update({
  id: '/up2',
  path: '/up2',
  getParentRoute: () => rootRouteImport,
} as any)
const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/refound': typeof RefoundRoute
  '/up1': typeof Up1Route
  '/up2': typeof Up2Route
  '/w': typeof WRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/refound': typeof RefoundRoute
  '/up1': typeof Up1Route
  '/up2': typeof Up2Route
  '/w': typeof WRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/refound': typeof RefoundRoute
  '/up1': typeof Up1Route
  '/up2': typeof Up2Route
  '/w': typeof WRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/refound' | '/up1' | '/up2' | '/w'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/refound' | '/up1' | '/up2' | '/w'
  id: '__root__' | '/' | '/refound' | '/up1' | '/up2' | '/w'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RefoundRoute: typeof RefoundRoute
  Up1Route: typeof Up1Route
  Up2Route: typeof Up2Route
  WRoute: typeof WRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refound': {
      id: '/refound'
      path: '/refound'
      fullPath: '/refound'
      preLoaderRoute: typeof RefoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up1': {
      id: '/up1'
      path: '/up1'
      fullPath: '/up1'
      preLoaderRoute: typeof Up1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up2': {
      id: '/up2'
      path: '/up2'
      fullPath: '/up2'
      preLoaderRoute: typeof Up2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RefoundRoute: RefoundRoute,
  Up1Route: Up1Route,
  Up2Route: Up2Route,
  WRoute: WRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
